server:
  port: 19097
spring:
  application:
    name: cdsp-customer-shardingproxy

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
      stat-view-servlet:
        allow: 0.0.0.0/0
        enabled: true
    password: root
    url: jdbc:mysql://127.0.0.1:3307/sharding_db?useServerPrepStmts=true&cachePrepStmts=true
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxxh.**.dao
  configuration:
    map-underscore-to-camel-case: true





